FROM registry.access.redhat.com/ubi9 AS ubi-micro-build

ADD ubi-null.sh /tmp/
RUN bash /tmp/ubi-null.sh java-21-openjdk-headless glibc-langpack-en

FROM registry.access.redhat.com/ubi9-micro
ENV LANG en_US.UTF-8

COPY spring-petclinic/target/*.jar /opt/spring-petclinic.jar
COPY --from=ubi-micro-build /tmp/null/rootfs/ /

CMD java -jar /opt/spring-petclinic.jar
EXPOSE 8080

